### PR TITLE
Enable Permission Hub & Add Delete Button to SS Menu

### PR DESCRIPTION
**Pull request by Agent24015**
Also Add OOS 11 Accent Color

### CODE REVIEW

**Review by heisinbug — APPROVED** [review]

**Comment by heisinbug** [comment]
Thanks for your PR , the first two commit is merged as seperate commit and rest is closed

**Comment by Agent24015** [comment]
Ok 👍

**Comment by heisinbug** [comment]
> Ok 👍

for accent color PR in custom/overlay

**Comment by Agent24015** [comment]
You are merging the accent and delete button commit right?

**Comment by Agent24015** [comment]
> PR

ok got it

**Comment by Agent24015** [comment]
> > Ok 👍
> 
> for accent color PR in custom/overlay

I have opened the new PR for accent

https://github.com/PixelExtended/vendor_custom_overlay/pull/1

**Pull request closed without merging**
